import { RotateTitle } from "./RotateTitle";

export const config = {
  id: "rotate-title",
  title: "Framed",
  durationInFrames: 300,
  extraDuration: 0,
  fps: 30,
  template: RotateTitle,
  defaultProps: {
    name: "",
    tagline: "",
    logo: "",
    bgType: "video",
    bgVideo: "",
    bgImage: "",
  },
  height: 600,
  width: 1066,
  authors: ["VS"],
  inputPropsSchema: [
    {
      type: "file",
      defaultValue: "",
      defaultRef: "profile",
      accept: 'image/*',
      name: "Logo",
      key: "logo",
    },
    {
      type: "text",
      defaultValue: "",
      defaultRef: "profile",
      name: "Business Name",
      key: "name",
    },
    {
      type: "text",
      defaultValue: "",
      defaultRef: "profile",
      name: "Tagline",
      key: "tagline",
    },
    {
      type: "file",
      defaultValue: "",
      name: "Background Video",
      key: "bgVideo",
    },
    {
      type: "Boolean",
      defaultValue: "video",
      name: "Background Type",
      key: "bgType",
    },
    {
      type: "file",
      defaultValue: "",
      name: "Background Image",
      key: "bgImage",
    },
    {
      type: "file",
      defaultValue: "https://travel-content-studio.s3.amazonaws.com/vsvideos/Adventurous.mp4",
      name: "Video",
      key: "video",
    },
    {
      type: "file",
      defaultValue: "",
      name: "Audio",
      key: "audio",
    },
  ],
};
